global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Stealth sidecar instances
  - job_name: 'stealth-sidecar-1'
    static_configs:
      - targets: ['stealth-sidecar-1:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'stealth-sidecar-2'
    static_configs:
      - targets: ['stealth-sidecar-2:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'stealth-sidecar-3'
    static_configs:
      - targets: ['stealth-sidecar-3:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Lighthouse metrics (if available)
  - job_name: 'lighthouse'
    static_configs:
      - targets: ['lighthouse:5054']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Reth metrics (if available)
  - job_name: 'reth'
    static_configs:
      - targets: ['reth:9001']
    scrape_interval: 10s
    metrics_path: '/debug/metrics/prometheus'